#!/usr/bin/env python3
# =============================================================================
# .jcode/lib/handbook_phase3.py — Phase III: Hierarchical Synthesis (paper §3.2)
# =============================================================================
# Convierte (S, U_g) en handbook navegable:
#   - L1: overview.md
#   - L2: stages/<id>.md (uno por stage)
#   - L3: function cards (inline en stage pages)
#   - Z: registers.md
#   - index.md: navegación
#   - K_g.json: estado de resync
#   - cache_B.json: cache reutilizable
#   - frozen_entries.json: entries con locators rotos
# Paper ref: arXiv:2607.13285v1, Phase III
# =============================================================================

import hashlib
import json
import sys
from pathlib import Path
from datetime import datetime, timezone


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def generate_overview(pg: dict, mapping: dict) -> str:
    """Genera L1: overview.md — system orientation."""
    funcs = pg.get("functions", [])
    stages = mapping.get("stage_skeleton", {}).get("stages", [])
    leaf_mode = pg.get("leaf_mode", "function")

    md = f"""# Handbook Overview (L1)

> Auto-generated by `handbook_phase3.py` on {now_iso()}
> Paper ref: arXiv:2607.13285v1, §3.2 Phase III

## System architecture

- **Language**: {pg.get('language', 'python')}
- **Leaf mode**: `{leaf_mode}` ({'function-level' if leaf_mode == 'function' else 'file-level'} decomposition)
- **Files scanned**: {pg.get('files_scanned', 0)}
- **Functions**: {len(funcs)}
- **Call edges**: {len(pg.get('call_edges', []))}
- **State accesses**: {len(pg.get('state_accesses', []))}

## Execution model

The harness follows a 6-stage execution model:

| Stage | Description |
|-------|-------------|
"""
    for s in stages:
        md += f"| `{s['id']}` | {s['name']} — {s['description']} |\n"

    md += """
## Stage relationships

```
init → interpret → plan → execute → verify → handoff
                                         ↓
                                       (loop until closeout)
```

## Global state flow

State registers tracked (Vista Z):
- See `registers.md` for full list

## How to navigate

1. Read `index.md` for the table of stages and leaves.
2. For each stage of interest, open `stages/<id>.md`.
3. For state-register mutations, read `registers.md`.
4. For verification of code sites, run `handbook_verify.py`.

## Maintenance

This handbook is auto-regenerated by `handbook_resync.py` after every commit.
"""
    return md


def generate_index(pg: dict, mapping: dict) -> str:
    """Genera index.md — table of stages + leaves + registers."""
    funcs_by_stage = {}
    for fa in mapping.get("function_assignments", []):
        for stage in fa.get("stage_assignments", []):
            funcs_by_stage.setdefault(stage, []).append(fa)

    md = f"""# Handbook Index

> Auto-generated on {now_iso()}

## Stages ({len(mapping.get('stage_skeleton', {}).get('stages', []))})

| Stage | Functions | Link |
|-------|-----------|------|
"""
    for s in mapping.get("stage_skeleton", {}).get("stages", []):
        count = len(funcs_by_stage.get(s["id"], []))
        md += f"| `{s['id']}` | {s['name']} | {count} | [→](stages/{s['id']}.md) |\n"

    md += f"""
## Leaves ({len(mapping.get('function_assignments', []))})

Total function-level leaves. See individual stage pages for details.

## Registers

See [registers.md](registers.md) for state-register writers/readers.

## K_g (resync state)

See `.jcode/handbook/K_g.json` for full resync state.
"""
    return md


def generate_registers(pg: dict, mapping: dict) -> str:
    """Genera registers.md — Vista Z: writers/readers por state register."""
    state_accesses = pg.get("state_accesses", [])

    # Build a qualname → file map from mapping
    qualname_to_file = {}
    for fa in mapping.get("function_assignments", []):
        qualname_to_file[fa["qualname"]] = fa["file"]

    # Agrupar por attribute
    by_attr = {}
    for sa in state_accesses:
        attr = sa["attribute"]
        func = sa.get("function", "")
        file_ref = sa.get("file", "") or qualname_to_file.get(func, "unknown")
        by_attr.setdefault(attr, {"read": [], "write": []}).setdefault(sa["access"], []).append({
            "function": func,
            "file": file_ref,
            "line": sa.get("line", 0),
        })

    md = f"""# State Registers (Vista Z)

> Auto-generated on {now_iso()}
> Maps each state register to all writers and readers.

"""
    if not by_attr:
        md += "_No state registers detected yet._\n"
    else:
        for attr, accesses in sorted(by_attr.items()):
            md += f"## `{attr}`\n\n"
            md += "**Writers:**\n"
            for w in accesses.get("write", []):
                md += f"- `{w['function']}` ({w['file']}:{w['line']})\n"
            md += "\n**Readers:**\n"
            for r in accesses.get("read", []):
                md += f"- `{r['function']}` ({r['file']}:{r['line']})\n"
            md += "\n"

    md += """
## Maintenance

- **R-SYNC-1**: Cuando agregues un campo de estado nuevo, agrega entrada en este archivo en el mismo commit.
- **R-SYNC-2**: Si un campo tiene más de 5 writers, probablemente debería descomponerse en derived fields.
"""
    return md


def generate_stage_page(stage_id: str, stage_name: str, stage_desc: str, funcs: list, pg: dict) -> str:
    """Genera una stage page con cards por función."""
    # Build qualname → signature map from program graph
    qn_to_sig = {}
    for f in pg.get("functions", []):
        qn_to_sig[f["qualname"]] = f.get("signature", "(...)")

    md = f"""# Stage: {stage_id} — {stage_name}

> {stage_desc}

## Responsibilities

{stage_desc}

## Inputs / Outputs

- **Inputs**: harness state, user request
- **Outputs**: stage artifact (loop declaration, build artifact, verification result, handoff)

## Execution flow

See related functions below.

## State

Relevant state registers (see registers.md):
- (auto-detected from state_accesses)

## Internal units

**Functions in this stage**: {len(funcs)}

"""
    for fa in funcs:
        sig = qn_to_sig.get(fa["qualname"], "(...)")
        md += f"""### `{fa['qualname']}`

- **File**: `{fa['file']}`
- **Line range**: {fa['line_range'][0]}-{fa['line_range'][1]}
- **Signature**: `{sig}`
- **Purpose**: {fa['purpose']}

"""
    md += """
## Code anchors

Auto-generated. For verification, run `handbook_verify.py`.
"""
    return md


def generate_l3_entries(mapping: dict, pg: dict) -> dict:
    """Genera el dict l3_entries para cache_B."""
    # Build qualname → signature map from program graph
    qn_to_sig = {}
    for f in pg.get("functions", []):
        qn_to_sig[f["qualname"]] = f.get("signature", "(...)")

    l3 = {}
    for fa in mapping.get("function_assignments", []):
        qn = fa["qualname"]
        l3[qn] = {
            "qualname": qn,
            "file": fa["file"],
            "anchor": fa["qualname"],
            "line_range": fa["line_range"],
            "source_hash": "",
            "interface": qn_to_sig.get(qn, "(...)"),
            "behavior": fa["purpose"],
            "relations": {"stages": fa["stage_assignments"]},
            "register_interactions": [],
        }
    return l3


def compute_graph_hash(pg: dict) -> str:
    """Hash del program graph para K_g."""
    canonical = json.dumps(pg, sort_keys=True, separators=(",", ":"))
    return "sha256:" + hashlib.sha256(canonical.encode()).hexdigest()[:16]


def run_phase3(program_graph_path: str = ".jcode/handbook/program_graph.json",
               mapping_path: str = ".jcode/handbook/behavioral_mapping.json",
               handbook_dir: str = ".jcode/handbook") -> dict:
    """Ejecuta Phase III: Hierarchical Synthesis."""
    pg_path = Path(program_graph_path)
    mp_path = Path(mapping_path)
    if not pg_path.exists():
        print(f"[error] {program_graph_path} no existe", file=sys.stderr)
        sys.exit(1)
    if not mp_path.exists():
        print(f"[error] {mapping_path} no existe. Ejecuta Phase II primero.", file=sys.stderr)
        sys.exit(1)

    with open(pg_path) as f:
        pg = json.load(f)
    with open(mp_path) as f:
        mapping = json.load(f)

    handbook_path = Path(handbook_dir)
    refs_path = handbook_path / "references"
    stages_path = refs_path / "stages"
    stages_path.mkdir(parents=True, exist_ok=True)

    # L1: overview.md
    overview = generate_overview(pg, mapping)
    (refs_path / "overview.md").write_text(overview)

    # index.md
    index_md = generate_index(pg, mapping)
    (refs_path / "index.md").write_text(index_md)

    # registers.md (Vista Z)
    registers = generate_registers(pg, mapping)
    (refs_path / "registers.md").write_text(registers)

    # L2: stages/<id>.md
    funcs_by_stage = {}
    for fa in mapping.get("function_assignments", []):
        for s in fa.get("stage_assignments", []):
            funcs_by_stage.setdefault(s, []).append(fa)

    for s in mapping.get("stage_skeleton", {}).get("stages", []):
        stage_funcs = funcs_by_stage.get(s["id"], [])
        page = generate_stage_page(s["id"], s["name"], s["description"], stage_funcs, pg)
        (stages_path / f"{s['id']}.md").write_text(page)

    # L3 entries
    l3_entries = generate_l3_entries(mapping, pg)

    # K_g: resync state
    K_g = {
        "leaf_mode": pg.get("leaf_mode", "function"),
        "program_graph_hash": compute_graph_hash(pg),
        "stage_skeleton": mapping.get("stage_skeleton"),
        "config": {"schema_version": 1, "generated_at": now_iso()},
    }
    (handbook_path / "K_g.json").write_text(json.dumps(K_g, indent=2))

    # cache_B: reusable artifacts
    cache_B = {
        "l3_entries": l3_entries,
        "l2_pages": sorted([p.name for p in stages_path.glob("*.md")]),
        "l1_overview": "overview.md",
    }
    (handbook_path / "cache_B.json").write_text(json.dumps(cache_B, indent=2))

    # frozen_entries: vacíos al inicio
    frozen = []
    (handbook_path / "frozen_entries.json").write_text(json.dumps(frozen, indent=2))

    print(f"[ok] Phase III: {len(l3_entries)} L3 entries, "
          f"{len(mapping.get('stage_skeleton', {}).get('stages', []))} state registers, "
          f"{len(frozen)} frozen")
    print(f"     Handbook saved to {handbook_dir}/references/")
    return {
        "l3_count": len(l3_entries),
        "stages": len(mapping.get("stage_skeleton", {}).get("stages", [])),
        "frozen": len(frozen),
    }


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Handbook Phase III: Hierarchical Synthesis")
    parser.add_argument("--program-graph", default=".jcode/handbook/program_graph.json")
    parser.add_argument("--mapping", default=".jcode/handbook/behavioral_mapping.json")
    parser.add_argument("--output", default=".jcode/handbook")
    args = parser.parse_args()
    run_phase3(args.program_graph, args.mapping, args.output)


if __name__ == "__main__":
    main()