#!/usr/bin/env bash
# test_pre-commit.sh — Test del hook pre-commit (auto-generado, ahora implementado)
set -uo pipefail
REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"
JCODE_DIR="$REPO_ROOT/.jcode"
HOOK="$JCODE_DIR/hooks/pre-commit.sh"
pass() { printf "  PASS  %s\n" "$*"; }
fail() { printf "  FAIL  %s\n" "$*" >&2; exit 1; }

echo "=== pre-commit.sh — validaciones ==="

echo "[1] Hook existe y ejecutable..."
[[ -x "$HOOK" ]] || fail "Hook no ejecutable"
pass "Hook ejecutable"

echo "[2] Hook tiene las 6 validaciones..."
for v in "V1.*HF Gate" "V2.*Sibling test" "V3.*Tests críticos" "V4.*fixed_check" "V5.*Cross-consumer" "V6.*set"; do
  grep -q "$v" "$HOOK" || fail "Falta $v"
done
pass "6 validaciones declaradas"

echo "[3] Hook bloquea commit con --no-verify override logged..."
TMPDIR=$(mktemp -d)
cd "$TMPDIR"
git init -q
git config user.email test@test.com
git config user.name test
mkdir -p .jcode/logs
echo "x" > a
git add a
# Override con razón
OVERRIDE_REASON_OVERRIDE="test override" bash "$HOOK" --no-verify
rc=$?
[[ $rc -eq 0 ]] || fail "Override no debería bloquear (rc=$rc)"
# Verificar log en el cwd actual (TMPDIR/.jcode/logs)
grep -q "OVERRIDE usado" .jcode/logs/pre-commit.log || fail "Override no loggeado en .jcode/logs/pre-commit.log"
pass "Override registrado en log"
rm -rf "$TMPDIR"

echo "[4] Hook genera stub para scripts sin test..."
# Test estático: la lógica de auto-generación existe en el hook
grep -q "AUTO-GENERATED by pre-commit" "$HOOK" || fail "Falta template AUTO-GENERATED"
grep -q 'cat > "\$stub"' "$HOOK" || fail "Falta lógica de creación de stub"
grep -q "chmod +x \"\$stub\"" "$HOOK" || fail "Falta chmod +x"
pass "Lógica de auto-generación de stubs presente"

echo "[5] Oracle exit codes consistentes..."
cd "$REPO_ROOT"
oracle_exit=$(REPO_ROOT="$REPO_ROOT" python3 "$JCODE_DIR/lib/oracle.py" >/dev/null 2>&1; echo $?)
if [[ "$oracle_exit" =~ ^[0-3]$ ]]; then
  pass "Oracle exit code válido: $oracle_exit"
else
  fail "Oracle exit code inválido: $oracle_exit"
fi

echo ""
echo "✅ pre-commit.sh: 5 checks validados"
exit 0
