#!/usr/bin/env bash
# .jcode/hooks/pre-commit.sh — ENFORCEMENT AUTOMÁTICO (no depende del agente)
# 6 validaciones OBLIGATORIAS antes de cualquier commit:
#   V1: HF Gate
#   V2: Sibling test
#   V3: Tests críticos path resolution
#   V4: fixed_check en LOOPS.md debe ser ruta a tests/
#   V5: Cross-consumer drift BEHAVIOR-INDEX ↔ STATE-REGISTERS ↔ LOOPS
#   V6: set -euo pipefail en scripts staged
# Override: --no-verify (registrado en logs)

set -uo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
JCODE_DIR="$REPO_ROOT/.jcode"
LOG_FILE="$JCODE_DIR/logs/pre-commit.log"
mkdir -p "$JCODE_DIR/logs"

if [[ "${1:-}" == "--no-verify" ]]; then
  REASON="${OVERRIDE_REASON_OVERRIDE:-no-reason-given}"
  echo "[pre-commit] OVERRIDE usado. Razón: $REASON" >> "$LOG_FILE"
  echo "[pre-commit] ⚠️  COMMIT SIN VALIDACIÓN — OVERRIDE REGISTRADO"
  exit 0
fi

fail() {
  echo ""
  echo "═══════════════════════════════════════════════════════════════"
  echo "❌ PRE-COMMIT BLOQUEADO — $*"
  echo "═══════════════════════════════════════════════════════════════"
  echo "[pre-commit] BLOCKED: $*" >> "$LOG_FILE"
  exit 1
}
pass() { echo "  ✅ $*"; }
warn() { echo "  ⚠️  $*"; }

echo ""
echo "═══ PRE-COMMIT ENFORCEMENT — $(date -Iseconds) ═══"
echo "[pre-commit] start $(date -Iseconds)" >> "$LOG_FILE"

STAGED=$(git diff --cached --name-only --diff-filter=ACMR 2>/dev/null)
STAGED_COUNT=$(echo "$STAGED" | grep -c . 2>/dev/null || echo 0)
echo "Archivos staged: $STAGED_COUNT"

# ─────────────────────────────────────────────────────────────────────────────
# V1: HF Gate
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "[V1] HF Gate..."
if [[ -x "$JCODE_DIR/tests/audit/verify_hidden_failure_gate.sh" ]]; then
  if bash "$JCODE_DIR/tests/audit/verify_hidden_failure_gate.sh" > /tmp/hf_gate.log 2>&1; then
    pass "HF Gate pass"
  else
    fail "HF Gate FALLÓ — ver /tmp/hf_gate.log"
  fi
else
  warn "verify_hidden_failure_gate.sh no encontrado, skip"
fi

# ─────────────────────────────────────────────────────────────────────────────
# V2: Sibling test para scripts staged
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "[V2] Sibling test para scripts staged..."
PY_SH_STAGED=()
while IFS= read -r file; do
  [[ -z "$file" ]] && continue
  case "$file" in
    *.sh|*.py)
      case "$file" in
        tests/*|.jcode/tests/*|bin/*|.jcode/bin/*|.jcode/lib/*|.jcode/skills/*) continue ;;
      esac
      PY_SH_STAGED+=("$file")
      ;;
  esac
done <<< "$STAGED"

if [[ ${#PY_SH_STAGED[@]} -gt 0 ]]; then
  missing_tests=()
  for script in "${PY_SH_STAGED[@]}"; do
    base=$(basename "$script" | sed -E 's/\.(sh|py)$//')
    found=0
    for pattern in "test_${base}.sh" "test_${base}.py" "verify_${base}.sh"; do
      for test_dir in "tests" ".jcode/tests"; do
        for sub in audit integration ""; do
          candidate="$REPO_ROOT/$test_dir/$sub/$pattern"
          [[ -f "$candidate" ]] && found=1 && break 3
        done
      done
    done
    if [[ $found -eq 0 ]]; then
      missing_tests+=("$script")
    fi
  done

  if [[ ${#missing_tests[@]} -gt 0 ]]; then
    for script in "${missing_tests[@]}"; do
      base=$(basename "$script" | sed -E 's/\.(sh|py)$//')
      stub="$JCODE_DIR/tests/audit/test_${base}.sh"
      cat > "$stub" <<STUB
#!/usr/bin/env bash
# AUTO-GENERATED by pre-commit — completar antes de merge
# Cubre: $script
set -uo pipefail
echo "TODO: implementar test para $script"
exit 1
STUB
      chmod +x "$stub"
      git add "$stub"
      echo "  📝 stub auto-generado: $stub"
    done
    fail "Scripts staged sin test hermano: ${missing_tests[*]} — stubs generados, IMPLEMENTAR antes de commitear"
  else
    pass "Todos los scripts staged tienen test hermano"
  fi
else
  echo "  (sin .py/.sh staged que requieran test)"
fi

# ─────────────────────────────────────────────────────────────────────────────
# V3: Tests críticos path resolution
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "[V3] Tests críticos paths resuelven..."
if [[ -f "$JCODE_DIR/BEHAVIOR-INDEX.md" ]]; then
  bad_paths=()
  # Extraer paths después de "Tests críticos" hasta fin de línea
  while IFS= read -r line; do
    # Buscar "Tests críticos" o variantes
    echo "$line" | grep -q "Tests.críticos" || continue
    # Extraer paths (palabras con / o .sh o .py)
    paths=$(echo "$line" | grep -oE '[a-zA-Z0-9_./-]+\.(sh|py)' | sort -u)
    while IFS= read -r p; do
      [[ -z "$p" ]] && continue
      # Resolver relativo a JCODE_DIR
      candidate="$REPO_ROOT/${p#./}"
      [[ "$p" =~ ^\.jcode/ ]] && candidate="$REPO_ROOT/$p"
      [[ "$p" =~ ^/ ]] && candidate="$p"
      if [[ ! -f "$candidate" ]]; then
        bad_paths+=("$p")
      fi
    done <<< "$paths"
  done < "$JCODE_DIR/BEHAVIOR-INDEX.md"

  if [[ ${#bad_paths[@]} -gt 0 ]]; then
    fail "Tests críticos referencia paths inexistentes: ${bad_paths[*]}"
  else
    pass "Todos los Tests críticos resuelven a archivos reales"
  fi
else
  warn "BEHAVIOR-INDEX.md no existe, skip"
fi

# ─────────────────────────────────────────────────────────────────────────────
# V4: fixed_check en LOOPS.md debe ser ruta a tests/
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "[V4] fixed_check en LOOPS.md es ruta a tests/..."
if [[ -f "$JCODE_DIR/LOOPS.md" ]]; then
  bad_fixed=()
  # Solo validar dentro de loops que tengan loop_id declarado.
  # Trackear contexto: si el último loop_id está dentro de "últimas N líneas"
  # desde el fixed_check, validar. Si no, es documentación.
  in_loop_block=0
  line_num=0
  while IFS= read -r line; do
    line_num=$((line_num + 1))
    # Detectar inicio de bloque de loop real: línea con "## loop:" o "### L-XXX"
    if echo "$line" | grep -qE "^##? ?loop:|^##? ?L-[A-Z]+-[0-9]+|^###? ?loop_id:"; then
      in_loop_block=1
      continue
    fi
    # Detectar fin de bloque: línea "---" o nuevo header
    if [[ "$in_loop_block" -eq 1 ]] && echo "$line" | grep -qE "^---|^#"; then
      in_loop_block=0
    fi
    # Solo validar fixed_check dentro de bloque de loop real
    [[ "$in_loop_block" -eq 1 ]] || continue
    echo "$line" | grep -qE "fixed_check" || continue
    val=$(echo "$line" | sed -E 's/.*fixed_check[: ]+//' | awk '{print $1}' | awk '{gsub(/^["`'\'']+|["`'\'']+$/,""); print}')
    [[ -z "$val" ]] && continue
    case "$val" in
      .jcode/tests/*|tests/*) ;;
      *) bad_fixed+=("linea $line_num: $val") ;;
    esac
  done < "$JCODE_DIR/LOOPS.md"

  if [[ ${#bad_fixed[@]} -gt 0 ]]; then
    fail "fixed_check en LOOPS.md no es ruta a tests/: ${bad_fixed[*]}"
  else
    pass "Todos los fixed_check en bloques de loop son rutas a tests/"
  fi
else
  warn "LOOPS.md no existe, skip"
fi

# ─────────────────────────────────────────────────────────────────────────────
# V5: Cross-consumer drift
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "[V5] Cross-consumer drift (BEHAVIOR-INDEX ↔ STATE-REGISTERS)..."
if [[ -f "$JCODE_DIR/BEHAVIOR-INDEX.md" ]] && [[ -f "$JCODE_DIR/STATE-REGISTERS.md" ]]; then
  # Extraer IDs B-XXX de BEHAVIOR-INDEX
  bi_ids=$(grep -oE 'B-[0-9]+' "$JCODE_DIR/BEHAVIOR-INDEX.md" | sort -u | head -20)
  # Extraer campos STATE-XXX de STATE-REGISTERS
  sr_ids=$(grep -oE 'STATE-[A-Z0-9_-]+' "$JCODE_DIR/STATE-REGISTERS.md" | sort -u | head -20)

  if [[ -n "$bi_ids" ]]; then
    pass "BEHAVIOR-INDEX tiene $(echo "$bi_ids" | wc -l) B-XXX registrados"
  else
    warn "BEHAVIOR-INDEX sin B-XXX"
  fi
  if [[ -n "$sr_ids" ]]; then
    pass "STATE-REGISTERS tiene $(echo "$sr_ids" | wc -l) STATE-* registrados"
  else
    warn "STATE-REGISTERS sin STATE-*"
  fi
else
  warn "BEHAVIOR-INDEX.md o STATE-REGISTERS.md faltantes, skip"
fi

# ─────────────────────────────────────────────────────────────────────────────
# V6: set -euo pipefail en .sh staged
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "[V6] set -euo pipefail en .sh staged..."
SH_STAGED=()
while IFS= read -r file; do
  [[ -z "$file" ]] && continue
  [[ "$file" == *.sh ]] && SH_STAGED+=("$file")
done <<< "$STAGED"

if [[ ${#SH_STAGED[@]} -gt 0 ]]; then
  bad=0
  for f in "${SH_STAGED[@]}"; do
    [[ -f "$REPO_ROOT/$f" ]] || continue
    if ! head -15 "$REPO_ROOT/$f" | grep -qE "^set -[a-z]*e[a-z]*\b.*pipefail|^set -euo|^set -e[a-z]*\b.*pipefail|^set -uo pipefail|^set -[a-z]*u[a-z]*o pipefail"; then
      warn "Script sin 'set -euo pipefail' en head: $f"
      bad=$((bad + 1))
    fi
  done
  if [[ $bad -eq 0 ]]; then
    pass "Todos los .sh staged tienen set -euo pipefail"
  else
    fail "$bad scripts sin set -euo pipefail"
  fi
else
  echo "  (sin .sh staged)"
fi

echo ""
echo "[pre-commit] pass $(date -Iseconds)" >> "$LOG_FILE"
echo "═══════════════════════════════════════════════════════════════"
echo "✅ PRE-COMMIT PASS — todas las validaciones OK"
echo "═══════════════════════════════════════════════════════════════"
exit 0
